// Code generated by go-swagger; DO NOT EDIT.

package system_fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeflectorParams creates a new DeflectorParams object
// with the default values initialized.
func NewDeflectorParams() *DeflectorParams {
	var ()
	return &DeflectorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeflectorParamsWithTimeout creates a new DeflectorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeflectorParamsWithTimeout(timeout time.Duration) *DeflectorParams {
	var ()
	return &DeflectorParams{

		timeout: timeout,
	}
}

// NewDeflectorParamsWithContext creates a new DeflectorParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeflectorParamsWithContext(ctx context.Context) *DeflectorParams {
	var ()
	return &DeflectorParams{

		Context: ctx,
	}
}

// NewDeflectorParamsWithHTTPClient creates a new DeflectorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeflectorParamsWithHTTPClient(client *http.Client) *DeflectorParams {
	var ()
	return &DeflectorParams{
		HTTPClient: client,
	}
}

/*DeflectorParams contains all the parameters to send to the API endpoint
for the deflector operation typically these are written to a http.Request
*/
type DeflectorParams struct {

	/*IndexSetID*/
	IndexSetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the deflector params
func (o *DeflectorParams) WithTimeout(timeout time.Duration) *DeflectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deflector params
func (o *DeflectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deflector params
func (o *DeflectorParams) WithContext(ctx context.Context) *DeflectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deflector params
func (o *DeflectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deflector params
func (o *DeflectorParams) WithHTTPClient(client *http.Client) *DeflectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deflector params
func (o *DeflectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIndexSetID adds the indexSetID to the deflector params
func (o *DeflectorParams) WithIndexSetID(indexSetID string) *DeflectorParams {
	o.SetIndexSetID(indexSetID)
	return o
}

// SetIndexSetID adds the indexSetId to the deflector params
func (o *DeflectorParams) SetIndexSetID(indexSetID string) {
	o.IndexSetID = indexSetID
}

// WriteToRequest writes these params to a swagger request
func (o *DeflectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param indexSetId
	if err := r.SetPathParam("indexSetId", o.IndexSetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
