// Code generated by go-swagger; DO NOT EDIT.

package system_fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeprecatedDeflectorParams creates a new DeprecatedDeflectorParams object
// with the default values initialized.
func NewDeprecatedDeflectorParams() *DeprecatedDeflectorParams {

	return &DeprecatedDeflectorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeprecatedDeflectorParamsWithTimeout creates a new DeprecatedDeflectorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeprecatedDeflectorParamsWithTimeout(timeout time.Duration) *DeprecatedDeflectorParams {

	return &DeprecatedDeflectorParams{

		timeout: timeout,
	}
}

// NewDeprecatedDeflectorParamsWithContext creates a new DeprecatedDeflectorParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeprecatedDeflectorParamsWithContext(ctx context.Context) *DeprecatedDeflectorParams {

	return &DeprecatedDeflectorParams{

		Context: ctx,
	}
}

// NewDeprecatedDeflectorParamsWithHTTPClient creates a new DeprecatedDeflectorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeprecatedDeflectorParamsWithHTTPClient(client *http.Client) *DeprecatedDeflectorParams {

	return &DeprecatedDeflectorParams{
		HTTPClient: client,
	}
}

/*DeprecatedDeflectorParams contains all the parameters to send to the API endpoint
for the deprecated deflector operation typically these are written to a http.Request
*/
type DeprecatedDeflectorParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the deprecated deflector params
func (o *DeprecatedDeflectorParams) WithTimeout(timeout time.Duration) *DeprecatedDeflectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deprecated deflector params
func (o *DeprecatedDeflectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deprecated deflector params
func (o *DeprecatedDeflectorParams) WithContext(ctx context.Context) *DeprecatedDeflectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deprecated deflector params
func (o *DeprecatedDeflectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deprecated deflector params
func (o *DeprecatedDeflectorParams) WithHTTPClient(client *http.Client) *DeprecatedDeflectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deprecated deflector params
func (o *DeprecatedDeflectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeprecatedDeflectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
