// Code generated by go-swagger; DO NOT EDIT.

package system_indices_index_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RebuildIndexReader is a Reader for the RebuildIndex structure.
type RebuildIndexReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RebuildIndexReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRebuildIndexOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewRebuildIndexAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRebuildIndexOK creates a RebuildIndexOK with default headers values
func NewRebuildIndexOK() *RebuildIndexOK {
	return &RebuildIndexOK{}
}

/*RebuildIndexOK handles this case with default header values.

No response was specified
*/
type RebuildIndexOK struct {
}

func (o *RebuildIndexOK) Error() string {
	return fmt.Sprintf("[POST /system/indices/ranges/{index: [a-z_0-9-]+}/rebuild][%d] rebuildIndexOK ", 200)
}

func (o *RebuildIndexOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRebuildIndexAccepted creates a RebuildIndexAccepted with default headers values
func NewRebuildIndexAccepted() *RebuildIndexAccepted {
	return &RebuildIndexAccepted{}
}

/*RebuildIndexAccepted handles this case with default header values.

Rebuild/sync system job triggered.
*/
type RebuildIndexAccepted struct {
}

func (o *RebuildIndexAccepted) Error() string {
	return fmt.Sprintf("[POST /system/indices/ranges/{index: [a-z_0-9-]+}/rebuild][%d] rebuildIndexAccepted ", 202)
}

func (o *RebuildIndexAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
