// Code generated by go-swagger; DO NOT EDIT.

package system_cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// NewExportBundleParams creates a new ExportBundleParams object
// with the default values initialized.
func NewExportBundleParams() *ExportBundleParams {
	var ()
	return &ExportBundleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportBundleParamsWithTimeout creates a new ExportBundleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportBundleParamsWithTimeout(timeout time.Duration) *ExportBundleParams {
	var ()
	return &ExportBundleParams{

		timeout: timeout,
	}
}

// NewExportBundleParamsWithContext creates a new ExportBundleParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportBundleParamsWithContext(ctx context.Context) *ExportBundleParams {
	var ()
	return &ExportBundleParams{

		Context: ctx,
	}
}

// NewExportBundleParamsWithHTTPClient creates a new ExportBundleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportBundleParamsWithHTTPClient(client *http.Client) *ExportBundleParams {
	var ()
	return &ExportBundleParams{
		HTTPClient: client,
	}
}

/*ExportBundleParams contains all the parameters to send to the API endpoint
for the export bundle operation typically these are written to a http.Request
*/
type ExportBundleParams struct {

	/*ExportBundle
	  Export content pack

	*/
	ExportBundle *models.ExportBundle

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export bundle params
func (o *ExportBundleParams) WithTimeout(timeout time.Duration) *ExportBundleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export bundle params
func (o *ExportBundleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export bundle params
func (o *ExportBundleParams) WithContext(ctx context.Context) *ExportBundleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export bundle params
func (o *ExportBundleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export bundle params
func (o *ExportBundleParams) WithHTTPClient(client *http.Client) *ExportBundleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export bundle params
func (o *ExportBundleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExportBundle adds the exportBundle to the export bundle params
func (o *ExportBundleParams) WithExportBundle(exportBundle *models.ExportBundle) *ExportBundleParams {
	o.SetExportBundle(exportBundle)
	return o
}

// SetExportBundle adds the exportBundle to the export bundle params
func (o *ExportBundleParams) SetExportBundle(exportBundle *models.ExportBundle) {
	o.ExportBundle = exportBundle
}

// WriteToRequest writes these params to a swagger request
func (o *ExportBundleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExportBundle != nil {
		if err := r.SetBodyParam(o.ExportBundle); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
