// Code generated by go-swagger; DO NOT EDIT.

package system_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAllParams creates a new AllParams object
// with the default values initialized.
func NewAllParams() *AllParams {
	var ()
	return &AllParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAllParamsWithTimeout creates a new AllParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAllParamsWithTimeout(timeout time.Duration) *AllParams {
	var ()
	return &AllParams{

		timeout: timeout,
	}
}

// NewAllParamsWithContext creates a new AllParams object
// with the default values initialized, and the ability to set a context for a request
func NewAllParamsWithContext(ctx context.Context) *AllParams {
	var ()
	return &AllParams{

		Context: ctx,
	}
}

// NewAllParamsWithHTTPClient creates a new AllParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAllParamsWithHTTPClient(client *http.Client) *AllParams {
	var ()
	return &AllParams{
		HTTPClient: client,
	}
}

/*AllParams contains all the parameters to send to the API endpoint
for the all operation typically these are written to a http.Request
*/
type AllParams struct {

	/*Page
	  Page

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the all params
func (o *AllParams) WithTimeout(timeout time.Duration) *AllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the all params
func (o *AllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the all params
func (o *AllParams) WithContext(ctx context.Context) *AllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the all params
func (o *AllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the all params
func (o *AllParams) WithHTTPClient(client *http.Client) *AllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the all params
func (o *AllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the all params
func (o *AllParams) WithPage(page *int64) *AllParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the all params
func (o *AllParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *AllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
