// Code generated by go-swagger; DO NOT EDIT.

package system_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new system metrics API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for system metrics API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
All gets internal graylog system messages
*/
func (a *Client) All(params *AllParams, authInfo runtime.ClientAuthInfoWriter) (*AllOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAllParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "all",
		Method:             "GET",
		PathPattern:        "/system/messages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AllReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AllOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
