// Code generated by go-swagger; DO NOT EDIT.

package system_service_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PauseProcessingReader is a Reader for the PauseProcessing structure.
type PauseProcessingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PauseProcessingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPauseProcessingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPauseProcessingOK creates a PauseProcessingOK with default headers values
func NewPauseProcessingOK() *PauseProcessingOK {
	return &PauseProcessingOK{}
}

/*PauseProcessingOK handles this case with default header values.

No response was specified
*/
type PauseProcessingOK struct {
}

func (o *PauseProcessingOK) Error() string {
	return fmt.Sprintf("[PUT /system/processing/pause][%d] pauseProcessingOK ", 200)
}

func (o *PauseProcessingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
