// Code generated by go-swagger; DO NOT EDIT.

package system_indices_retention

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetDefaultParams creates a new SetDefaultParams object
// with the default values initialized.
func NewSetDefaultParams() *SetDefaultParams {
	var ()
	return &SetDefaultParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetDefaultParamsWithTimeout creates a new SetDefaultParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetDefaultParamsWithTimeout(timeout time.Duration) *SetDefaultParams {
	var ()
	return &SetDefaultParams{

		timeout: timeout,
	}
}

// NewSetDefaultParamsWithContext creates a new SetDefaultParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetDefaultParamsWithContext(ctx context.Context) *SetDefaultParams {
	var ()
	return &SetDefaultParams{

		Context: ctx,
	}
}

// NewSetDefaultParamsWithHTTPClient creates a new SetDefaultParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetDefaultParamsWithHTTPClient(client *http.Client) *SetDefaultParams {
	var ()
	return &SetDefaultParams{
		HTTPClient: client,
	}
}

/*SetDefaultParams contains all the parameters to send to the API endpoint
for the set default operation typically these are written to a http.Request
*/
type SetDefaultParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set default params
func (o *SetDefaultParams) WithTimeout(timeout time.Duration) *SetDefaultParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set default params
func (o *SetDefaultParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set default params
func (o *SetDefaultParams) WithContext(ctx context.Context) *SetDefaultParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set default params
func (o *SetDefaultParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set default params
func (o *SetDefaultParams) WithHTTPClient(client *http.Client) *SetDefaultParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set default params
func (o *SetDefaultParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the set default params
func (o *SetDefaultParams) WithID(id string) *SetDefaultParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set default params
func (o *SetDefaultParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SetDefaultParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
