// Code generated by go-swagger; DO NOT EDIT.

package streams_streamid_alerts_alert_id_history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// GetForAlertReader is a Reader for the GetForAlert structure.
type GetForAlertReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetForAlertReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetForAlertOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetForAlertOK creates a GetForAlertOK with default headers values
func NewGetForAlertOK() *GetForAlertOK {
	return &GetForAlertOK{}
}

/*GetForAlertOK handles this case with default header values.

No response was specified
*/
type GetForAlertOK struct {
	Payload *models.AlarmCallbackHistoryListSummary
}

func (o *GetForAlertOK) Error() string {
	return fmt.Sprintf("[GET /streams/{streamid}/alerts/{alertId}/history][%d] getForAlertOK  %+v", 200, o.Payload)
}

func (o *GetForAlertOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlarmCallbackHistoryListSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
