// Code generated by go-swagger; DO NOT EDIT.

package system_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AvailableReader is a Reader for the Available structure.
type AvailableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvailableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAvailableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAvailableOK creates a AvailableOK with default headers values
func NewAvailableOK() *AvailableOK {
	return &AvailableOK{}
}

/*AvailableOK handles this case with default header values.

No response was specified
*/
type AvailableOK struct {
	Payload AvailableOKBody
}

func (o *AvailableOK) Error() string {
	return fmt.Sprintf("[GET /system/outputs/available][%d] availableOK  %+v", 200, o.Payload)
}

func (o *AvailableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*AvailableOKBody available o k body
swagger:model AvailableOKBody
*/
type AvailableOKBody interface{}
