// Code generated by go-swagger; DO NOT EDIT.

package system_grok

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisplayGettingStartedParams creates a new DisplayGettingStartedParams object
// with the default values initialized.
func NewDisplayGettingStartedParams() *DisplayGettingStartedParams {

	return &DisplayGettingStartedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisplayGettingStartedParamsWithTimeout creates a new DisplayGettingStartedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisplayGettingStartedParamsWithTimeout(timeout time.Duration) *DisplayGettingStartedParams {

	return &DisplayGettingStartedParams{

		timeout: timeout,
	}
}

// NewDisplayGettingStartedParamsWithContext creates a new DisplayGettingStartedParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisplayGettingStartedParamsWithContext(ctx context.Context) *DisplayGettingStartedParams {

	return &DisplayGettingStartedParams{

		Context: ctx,
	}
}

// NewDisplayGettingStartedParamsWithHTTPClient creates a new DisplayGettingStartedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDisplayGettingStartedParamsWithHTTPClient(client *http.Client) *DisplayGettingStartedParams {

	return &DisplayGettingStartedParams{
		HTTPClient: client,
	}
}

/*DisplayGettingStartedParams contains all the parameters to send to the API endpoint
for the display getting started operation typically these are written to a http.Request
*/
type DisplayGettingStartedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the display getting started params
func (o *DisplayGettingStartedParams) WithTimeout(timeout time.Duration) *DisplayGettingStartedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the display getting started params
func (o *DisplayGettingStartedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the display getting started params
func (o *DisplayGettingStartedParams) WithContext(ctx context.Context) *DisplayGettingStartedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the display getting started params
func (o *DisplayGettingStartedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the display getting started params
func (o *DisplayGettingStartedParams) WithHTTPClient(client *http.Client) *DisplayGettingStartedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the display getting started params
func (o *DisplayGettingStartedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DisplayGettingStartedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
