// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SetActionReader is a Reader for the SetAction structure.
type SetActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSetActionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetActionOK creates a SetActionOK with default headers values
func NewSetActionOK() *SetActionOK {
	return &SetActionOK{}
}

/*SetActionOK handles this case with default header values.

No response was specified
*/
type SetActionOK struct {
}

func (o *SetActionOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/org.graylog.plugins.collector/collectors/{collectorId}/action][%d] setActionOK ", 200)
}

func (o *SetActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetActionBadRequest creates a SetActionBadRequest with default headers values
func NewSetActionBadRequest() *SetActionBadRequest {
	return &SetActionBadRequest{}
}

/*SetActionBadRequest handles this case with default header values.

The supplied action is not valid.
*/
type SetActionBadRequest struct {
}

func (o *SetActionBadRequest) Error() string {
	return fmt.Sprintf("[PUT /plugins/org.graylog.plugins.collector/collectors/{collectorId}/action][%d] setActionBadRequest ", 400)
}

func (o *SetActionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
