// Code generated by go-swagger; DO NOT EDIT.

package system_indexer_overview

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewClosedParams creates a new ClosedParams object
// with the default values initialized.
func NewClosedParams() *ClosedParams {

	return &ClosedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewClosedParamsWithTimeout creates a new ClosedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewClosedParamsWithTimeout(timeout time.Duration) *ClosedParams {

	return &ClosedParams{

		timeout: timeout,
	}
}

// NewClosedParamsWithContext creates a new ClosedParams object
// with the default values initialized, and the ability to set a context for a request
func NewClosedParamsWithContext(ctx context.Context) *ClosedParams {

	return &ClosedParams{

		Context: ctx,
	}
}

// NewClosedParamsWithHTTPClient creates a new ClosedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewClosedParamsWithHTTPClient(client *http.Client) *ClosedParams {

	return &ClosedParams{
		HTTPClient: client,
	}
}

/*ClosedParams contains all the parameters to send to the API endpoint
for the closed operation typically these are written to a http.Request
*/
type ClosedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the closed params
func (o *ClosedParams) WithTimeout(timeout time.Duration) *ClosedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the closed params
func (o *ClosedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the closed params
func (o *ClosedParams) WithContext(ctx context.Context) *ClosedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the closed params
func (o *ClosedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the closed params
func (o *ClosedParams) WithHTTPClient(client *http.Client) *ClosedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the closed params
func (o *ClosedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ClosedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
