// Code generated by go-swagger; DO NOT EDIT.

package system_indexer_overview

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIndexSetListParams creates a new IndexSetListParams object
// with the default values initialized.
func NewIndexSetListParams() *IndexSetListParams {
	var ()
	return &IndexSetListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIndexSetListParamsWithTimeout creates a new IndexSetListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIndexSetListParamsWithTimeout(timeout time.Duration) *IndexSetListParams {
	var ()
	return &IndexSetListParams{

		timeout: timeout,
	}
}

// NewIndexSetListParamsWithContext creates a new IndexSetListParams object
// with the default values initialized, and the ability to set a context for a request
func NewIndexSetListParamsWithContext(ctx context.Context) *IndexSetListParams {
	var ()
	return &IndexSetListParams{

		Context: ctx,
	}
}

// NewIndexSetListParamsWithHTTPClient creates a new IndexSetListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIndexSetListParamsWithHTTPClient(client *http.Client) *IndexSetListParams {
	var ()
	return &IndexSetListParams{
		HTTPClient: client,
	}
}

/*IndexSetListParams contains all the parameters to send to the API endpoint
for the index set list operation typically these are written to a http.Request
*/
type IndexSetListParams struct {

	/*IndexSetID*/
	IndexSetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the index set list params
func (o *IndexSetListParams) WithTimeout(timeout time.Duration) *IndexSetListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the index set list params
func (o *IndexSetListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the index set list params
func (o *IndexSetListParams) WithContext(ctx context.Context) *IndexSetListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the index set list params
func (o *IndexSetListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the index set list params
func (o *IndexSetListParams) WithHTTPClient(client *http.Client) *IndexSetListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the index set list params
func (o *IndexSetListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIndexSetID adds the indexSetID to the index set list params
func (o *IndexSetListParams) WithIndexSetID(indexSetID string) *IndexSetListParams {
	o.SetIndexSetID(indexSetID)
	return o
}

// SetIndexSetID adds the indexSetId to the index set list params
func (o *IndexSetListParams) SetIndexSetID(indexSetID string) {
	o.IndexSetID = indexSetID
}

// WriteToRequest writes these params to a swagger request
func (o *IndexSetListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param indexSetId
	if err := r.SetPathParam("indexSetId", o.IndexSetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
