// Code generated by go-swagger; DO NOT EDIT.

package system_indexer_overview

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// IndexSetListReader is a Reader for the IndexSetList structure.
type IndexSetListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexSetListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIndexSetListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIndexSetListOK creates a IndexSetListOK with default headers values
func NewIndexSetListOK() *IndexSetListOK {
	return &IndexSetListOK{}
}

/*IndexSetListOK handles this case with default header values.

No response was specified
*/
type IndexSetListOK struct {
	Payload *models.AllIndices
}

func (o *IndexSetListOK) Error() string {
	return fmt.Sprintf("[GET /system/indexer/indices/{indexSetId}/list][%d] indexSetListOK  %+v", 200, o.Payload)
}

func (o *IndexSetListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AllIndices)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
