// Code generated by go-swagger; DO NOT EDIT.

package search_universal_absolute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// GetMembersReader is a Reader for the GetMembers structure.
type GetMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMembersOK creates a GetMembersOK with default headers values
func NewGetMembersOK() *GetMembersOK {
	return &GetMembersOK{}
}

/*GetMembersOK handles this case with default header values.

No response was specified
*/
type GetMembersOK struct {
	Payload *models.RoleMembershipResponse
}

func (o *GetMembersOK) Error() string {
	return fmt.Sprintf("[GET /roles/{rolename}/members][%d] getMembersOK  %+v", 200, o.Payload)
}

func (o *GetMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleMembershipResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
