// Code generated by go-swagger; DO NOT EDIT.

package system_messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewConfigParams creates a new ConfigParams object
// with the default values initialized.
func NewConfigParams() *ConfigParams {

	return &ConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewConfigParamsWithTimeout creates a new ConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewConfigParamsWithTimeout(timeout time.Duration) *ConfigParams {

	return &ConfigParams{

		timeout: timeout,
	}
}

// NewConfigParamsWithContext creates a new ConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewConfigParamsWithContext(ctx context.Context) *ConfigParams {

	return &ConfigParams{

		Context: ctx,
	}
}

// NewConfigParamsWithHTTPClient creates a new ConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewConfigParamsWithHTTPClient(client *http.Client) *ConfigParams {

	return &ConfigParams{
		HTTPClient: client,
	}
}

/*ConfigParams contains all the parameters to send to the API endpoint
for the config operation typically these are written to a http.Request
*/
type ConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the config params
func (o *ConfigParams) WithTimeout(timeout time.Duration) *ConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the config params
func (o *ConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the config params
func (o *ConfigParams) WithContext(ctx context.Context) *ConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the config params
func (o *ConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the config params
func (o *ConfigParams) WithHTTPClient(client *http.Client) *ConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the config params
func (o *ConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
