// Code generated by go-swagger; DO NOT EDIT.

package system_indexer_failures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewClusterNameParams creates a new ClusterNameParams object
// with the default values initialized.
func NewClusterNameParams() *ClusterNameParams {

	return &ClusterNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewClusterNameParamsWithTimeout creates a new ClusterNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewClusterNameParamsWithTimeout(timeout time.Duration) *ClusterNameParams {

	return &ClusterNameParams{

		timeout: timeout,
	}
}

// NewClusterNameParamsWithContext creates a new ClusterNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewClusterNameParamsWithContext(ctx context.Context) *ClusterNameParams {

	return &ClusterNameParams{

		Context: ctx,
	}
}

// NewClusterNameParamsWithHTTPClient creates a new ClusterNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewClusterNameParamsWithHTTPClient(client *http.Client) *ClusterNameParams {

	return &ClusterNameParams{
		HTTPClient: client,
	}
}

/*ClusterNameParams contains all the parameters to send to the API endpoint
for the cluster name operation typically these are written to a http.Request
*/
type ClusterNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cluster name params
func (o *ClusterNameParams) WithTimeout(timeout time.Duration) *ClusterNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster name params
func (o *ClusterNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster name params
func (o *ClusterNameParams) WithContext(ctx context.Context) *ClusterNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster name params
func (o *ClusterNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster name params
func (o *ClusterNameParams) WithHTTPClient(client *http.Client) *ClusterNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster name params
func (o *ClusterNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
