// Code generated by go-swagger; DO NOT EDIT.

package system_indexer_failures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new system indexer failures API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for system indexer failures API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ClusterHealth gets cluster and shard health overview
*/
func (a *Client) ClusterHealth(params *ClusterHealthParams, authInfo runtime.ClientAuthInfoWriter) (*ClusterHealthOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewClusterHealthParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "clusterHealth",
		Method:             "GET",
		PathPattern:        "/system/indexer/cluster/health",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ClusterHealthReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ClusterHealthOK), nil

}

/*
ClusterName gets the cluster name
*/
func (a *Client) ClusterName(params *ClusterNameParams, authInfo runtime.ClientAuthInfoWriter) (*ClusterNameOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewClusterNameParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "clusterName",
		Method:             "GET",
		PathPattern:        "/system/indexer/cluster/name",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ClusterNameReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ClusterNameOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
