// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AlertListSummary alert list summary
// swagger:model AlertListSummary
type AlertListSummary struct {

	// alerts
	Alerts AlertListSummaryAlerts `json:"alerts"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this alert list summary
func (m *AlertListSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AlertListSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertListSummary) UnmarshalBinary(b []byte) error {
	var res AlertListSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
