// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClusterStatsMongoDatabaseStatsDataFileVersion cluster stats mongo database stats data file version
// swagger:model clusterStatsMongoDatabaseStatsDataFileVersion
type ClusterStatsMongoDatabaseStatsDataFileVersion struct {

	// major
	Major int64 `json:"major,omitempty"`

	// minor
	Minor int64 `json:"minor,omitempty"`
}

// Validate validates this cluster stats mongo database stats data file version
func (m *ClusterStatsMongoDatabaseStatsDataFileVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterStatsMongoDatabaseStatsDataFileVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterStatsMongoDatabaseStatsDataFileVersion) UnmarshalBinary(b []byte) error {
	var res ClusterStatsMongoDatabaseStatsDataFileVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
