// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ConfigurationBundleDashboardsItemsDashboardWidgetsItems configuration bundle dashboards items dashboard widgets items
// swagger:model configurationBundleDashboardsItemsDashboardWidgetsItems
type ConfigurationBundleDashboardsItemsDashboardWidgetsItems struct {

	// cache time
	CacheTime int64 `json:"cache_time,omitempty"`

	// col
	Col int64 `json:"col,omitempty"`

	// configuration
	Configuration interface{} `json:"configuration,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// height
	Height int64 `json:"height,omitempty"`

	// row
	Row int64 `json:"row,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// width
	Width int64 `json:"width,omitempty"`
}

// Validate validates this configuration bundle dashboards items dashboard widgets items
func (m *ConfigurationBundleDashboardsItemsDashboardWidgetsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigurationBundleDashboardsItemsDashboardWidgetsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigurationBundleDashboardsItemsDashboardWidgetsItems) UnmarshalBinary(b []byte) error {
	var res ConfigurationBundleDashboardsItemsDashboardWidgetsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
