// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IndexSetStats index set stats
// swagger:model IndexSetStats
type IndexSetStats struct {

	// documents
	Documents int64 `json:"documents,omitempty"`

	// indices
	Indices int64 `json:"indices,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`
}

// Validate validates this index set stats
func (m *IndexSetStats) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IndexSetStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IndexSetStats) UnmarshalBinary(b []byte) error {
	var res IndexSetStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
