// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IndexInfoPrimaryShardsDocuments index info primary shards documents
// swagger:model indexInfoPrimaryShardsDocuments
type IndexInfoPrimaryShardsDocuments struct {

	// count
	Count int64 `json:"count,omitempty"`

	// deleted
	Deleted int64 `json:"deleted,omitempty"`
}

// Validate validates this index info primary shards documents
func (m *IndexInfoPrimaryShardsDocuments) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IndexInfoPrimaryShardsDocuments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IndexInfoPrimaryShardsDocuments) UnmarshalBinary(b []byte) error {
	var res IndexInfoPrimaryShardsDocuments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
