// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MessageProcessorsConfigWithDescriptors message processors config with descriptors
// swagger:model MessageProcessorsConfigWithDescriptors
type MessageProcessorsConfigWithDescriptors struct {

	// disabled processors
	DisabledProcessors []string `json:"disabled_processors"`

	// processor order
	ProcessorOrder MessageProcessorsConfigWithDescriptorsProcessorOrder `json:"processor_order"`
}

// Validate validates this message processors config with descriptors
func (m *MessageProcessorsConfigWithDescriptors) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisabledProcessors(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MessageProcessorsConfigWithDescriptors) validateDisabledProcessors(formats strfmt.Registry) error {

	if swag.IsZero(m.DisabledProcessors) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MessageProcessorsConfigWithDescriptors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MessageProcessorsConfigWithDescriptors) UnmarshalBinary(b []byte) error {
	var res MessageProcessorsConfigWithDescriptors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
