// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MongoStatsBuildInfo mongo stats build info
// swagger:model mongoStatsBuildInfo
type MongoStatsBuildInfo struct {

	// allocator
	Allocator string `json:"allocator,omitempty"`

	// bits
	Bits int64 `json:"bits,omitempty"`

	// compiler flags
	CompilerFlags string `json:"compiler_flags,omitempty"`

	// debug
	Debug bool `json:"debug,omitempty"`

	// git version
	GitVersion string `json:"git_version,omitempty"`

	// javascript engine
	JavascriptEngine string `json:"javascript_engine,omitempty"`

	// loader flags
	LoaderFlags string `json:"loader_flags,omitempty"`

	// max bson object size
	MaxBsonObjectSize int64 `json:"max_bson_object_size,omitempty"`

	// sys info
	SysInfo string `json:"sys_info,omitempty"`

	// version
	Version string `json:"version,omitempty"`

	// version array
	VersionArray []int64 `json:"version_array"`
}

// Validate validates this mongo stats build info
func (m *MongoStatsBuildInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVersionArray(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MongoStatsBuildInfo) validateVersionArray(formats strfmt.Registry) error {

	if swag.IsZero(m.VersionArray) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MongoStatsBuildInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MongoStatsBuildInfo) UnmarshalBinary(b []byte) error {
	var res MongoStatsBuildInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
