// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NodeSummary node summary
// swagger:model NodeSummary
type NodeSummary struct {

	// cluster id
	ClusterID string `json:"cluster_id,omitempty"`

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// is master
	IsMaster bool `json:"is_master,omitempty"`

	// last seen
	LastSeen string `json:"last_seen,omitempty"`

	// node id
	NodeID string `json:"node_id,omitempty"`

	// short node id
	ShortNodeID string `json:"short_node_id,omitempty"`

	// transport address
	TransportAddress string `json:"transport_address,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this node summary
func (m *NodeSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NodeSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeSummary) UnmarshalBinary(b []byte) error {
	var res NodeSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
