// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OsStatsMemory os stats memory
// swagger:model osStatsMemory
type OsStatsMemory struct {

	// actual free
	ActualFree int64 `json:"actual_free,omitempty"`

	// actual used
	ActualUsed int64 `json:"actual_used,omitempty"`

	// free
	Free int64 `json:"free,omitempty"`

	// free percent
	FreePercent int64 `json:"free_percent,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`

	// used
	Used int64 `json:"used,omitempty"`

	// used percent
	UsedPercent int64 `json:"used_percent,omitempty"`
}

// Validate validates this os stats memory
func (m *OsStatsMemory) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OsStatsMemory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OsStatsMemory) UnmarshalBinary(b []byte) error {
	var res OsStatsMemory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
