// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PipelineSourceErrorsItems pipeline source errors items
// swagger:model pipelineSourceErrorsItems
type PipelineSourceErrorsItems struct {

	// line
	Line int64 `json:"line,omitempty"`

	// position in line
	PositionInLine int64 `json:"position_in_line,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this pipeline source errors items
func (m *PipelineSourceErrorsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PipelineSourceErrorsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineSourceErrorsItems) UnmarshalBinary(b []byte) error {
	var res PipelineSourceErrorsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
