// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SimulationResponseSimulationTraceItems simulation response simulation trace items
// swagger:model simulationResponseSimulationTraceItems
type SimulationResponseSimulationTraceItems struct {

	// message
	Message string `json:"message,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`
}

// Validate validates this simulation response simulation trace items
func (m *SimulationResponseSimulationTraceItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SimulationResponseSimulationTraceItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SimulationResponseSimulationTraceItems) UnmarshalBinary(b []byte) error {
	var res SimulationResponseSimulationTraceItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
