// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StreamResponseRulesItems stream response rules items
// swagger:model streamResponseRulesItems
type StreamResponseRulesItems struct {

	// content pack
	ContentPack string `json:"content_pack,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// field
	Field string `json:"field,omitempty"`

	// fields
	Fields interface{} `json:"fields,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// inverted
	Inverted bool `json:"inverted,omitempty"`

	// stream id
	StreamID string `json:"stream_id,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// validations
	Validations interface{} `json:"validations,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this stream response rules items
func (m *StreamResponseRulesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var streamResponseRulesItemsTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["EXACT","REGEX","GREATER","SMALLER","PRESENCE","CONTAINS","ALWAYS_MATCH"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		streamResponseRulesItemsTypeTypePropEnum = append(streamResponseRulesItemsTypeTypePropEnum, v)
	}
}

const (
	// StreamResponseRulesItemsTypeEXACT captures enum value "EXACT"
	StreamResponseRulesItemsTypeEXACT string = "EXACT"
	// StreamResponseRulesItemsTypeREGEX captures enum value "REGEX"
	StreamResponseRulesItemsTypeREGEX string = "REGEX"
	// StreamResponseRulesItemsTypeGREATER captures enum value "GREATER"
	StreamResponseRulesItemsTypeGREATER string = "GREATER"
	// StreamResponseRulesItemsTypeSMALLER captures enum value "SMALLER"
	StreamResponseRulesItemsTypeSMALLER string = "SMALLER"
	// StreamResponseRulesItemsTypePRESENCE captures enum value "PRESENCE"
	StreamResponseRulesItemsTypePRESENCE string = "PRESENCE"
	// StreamResponseRulesItemsTypeCONTAINS captures enum value "CONTAINS"
	StreamResponseRulesItemsTypeCONTAINS string = "CONTAINS"
	// StreamResponseRulesItemsTypeALWAYSMATCH captures enum value "ALWAYS_MATCH"
	StreamResponseRulesItemsTypeALWAYSMATCH string = "ALWAYS_MATCH"
)

// prop value enum
func (m *StreamResponseRulesItems) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, streamResponseRulesItemsTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *StreamResponseRulesItems) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StreamResponseRulesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StreamResponseRulesItems) UnmarshalBinary(b []byte) error {
	var res StreamResponseRulesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
