// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateInputReader is a Reader for the CreateInput structure.
type CreateInputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateInputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateInputBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateInputOK creates a CreateInputOK with default headers values
func NewCreateInputOK() *CreateInputOK {
	return &CreateInputOK{}
}

/*CreateInputOK handles this case with default header values.

No response was specified
*/
type CreateInputOK struct {
}

func (o *CreateInputOK) Error() string {
	return fmt.Sprintf("[POST /plugins/org.graylog.plugins.collector/configurations/{id}/inputs][%d] createInputOK ", 200)
}

func (o *CreateInputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInputBadRequest creates a CreateInputBadRequest with default headers values
func NewCreateInputBadRequest() *CreateInputBadRequest {
	return &CreateInputBadRequest{}
}

/*CreateInputBadRequest handles this case with default header values.

The supplied request is not valid.
*/
type CreateInputBadRequest struct {
}

func (o *CreateInputBadRequest) Error() string {
	return fmt.Sprintf("[POST /plugins/org.graylog.plugins.collector/configurations/{id}/inputs][%d] createInputBadRequest ", 400)
}

func (o *CreateInputBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
