// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateInputParams creates a new CreateInputParams object
// with the default values initialized.
func NewCreateInputParams() *CreateInputParams {
	var ()
	return &CreateInputParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateInputParamsWithTimeout creates a new CreateInputParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateInputParamsWithTimeout(timeout time.Duration) *CreateInputParams {
	var ()
	return &CreateInputParams{

		timeout: timeout,
	}
}

// NewCreateInputParamsWithContext creates a new CreateInputParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateInputParamsWithContext(ctx context.Context) *CreateInputParams {
	var ()
	return &CreateInputParams{

		Context: ctx,
	}
}

// NewCreateInputParamsWithHTTPClient creates a new CreateInputParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateInputParamsWithHTTPClient(client *http.Client) *CreateInputParams {
	var ()
	return &CreateInputParams{
		HTTPClient: client,
	}
}

/*CreateInputParams contains all the parameters to send to the API endpoint
for the create input operation typically these are written to a http.Request
*/
type CreateInputParams struct {

	/*JSONBody*/
	JSONBody interface{}
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create input params
func (o *CreateInputParams) WithTimeout(timeout time.Duration) *CreateInputParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create input params
func (o *CreateInputParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create input params
func (o *CreateInputParams) WithContext(ctx context.Context) *CreateInputParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create input params
func (o *CreateInputParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create input params
func (o *CreateInputParams) WithHTTPClient(client *http.Client) *CreateInputParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create input params
func (o *CreateInputParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the create input params
func (o *CreateInputParams) WithJSONBody(jSONBody interface{}) *CreateInputParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the create input params
func (o *CreateInputParams) SetJSONBody(jSONBody interface{}) {
	o.JSONBody = jSONBody
}

// WithID adds the id to the create input params
func (o *CreateInputParams) WithID(id string) *CreateInputParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create input params
func (o *CreateInputParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInputParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
