// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateOutputReader is a Reader for the CreateOutput structure.
type CreateOutputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOutputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateOutputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateOutputBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateOutputOK creates a CreateOutputOK with default headers values
func NewCreateOutputOK() *CreateOutputOK {
	return &CreateOutputOK{}
}

/*CreateOutputOK handles this case with default header values.

No response was specified
*/
type CreateOutputOK struct {
}

func (o *CreateOutputOK) Error() string {
	return fmt.Sprintf("[POST /plugins/org.graylog.plugins.collector/configurations/{id}/outputs][%d] createOutputOK ", 200)
}

func (o *CreateOutputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOutputBadRequest creates a CreateOutputBadRequest with default headers values
func NewCreateOutputBadRequest() *CreateOutputBadRequest {
	return &CreateOutputBadRequest{}
}

/*CreateOutputBadRequest handles this case with default header values.

The supplied request is not valid.
*/
type CreateOutputBadRequest struct {
}

func (o *CreateOutputBadRequest) Error() string {
	return fmt.Sprintf("[POST /plugins/org.graylog.plugins.collector/configurations/{id}/outputs][%d] createOutputBadRequest ", 400)
}

func (o *CreateOutputBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
