// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSnippetReader is a Reader for the DeleteSnippet structure.
type DeleteSnippetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSnippetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSnippetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteSnippetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteSnippetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSnippetOK creates a DeleteSnippetOK with default headers values
func NewDeleteSnippetOK() *DeleteSnippetOK {
	return &DeleteSnippetOK{}
}

/*DeleteSnippetOK handles this case with default header values.

No response was specified
*/
type DeleteSnippetOK struct {
}

func (o *DeleteSnippetOK) Error() string {
	return fmt.Sprintf("[DELETE /plugins/org.graylog.plugins.collector/configurations/{id}/snippets/{snippetId}][%d] deleteSnippetOK ", 200)
}

func (o *DeleteSnippetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSnippetBadRequest creates a DeleteSnippetBadRequest with default headers values
func NewDeleteSnippetBadRequest() *DeleteSnippetBadRequest {
	return &DeleteSnippetBadRequest{}
}

/*DeleteSnippetBadRequest handles this case with default header values.

Invalid ObjectId.
*/
type DeleteSnippetBadRequest struct {
}

func (o *DeleteSnippetBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /plugins/org.graylog.plugins.collector/configurations/{id}/snippets/{snippetId}][%d] deleteSnippetBadRequest ", 400)
}

func (o *DeleteSnippetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSnippetNotFound creates a DeleteSnippetNotFound with default headers values
func NewDeleteSnippetNotFound() *DeleteSnippetNotFound {
	return &DeleteSnippetNotFound{}
}

/*DeleteSnippetNotFound handles this case with default header values.

Configuration or Snippet not found.
*/
type DeleteSnippetNotFound struct {
}

func (o *DeleteSnippetNotFound) Error() string {
	return fmt.Sprintf("[DELETE /plugins/org.graylog.plugins.collector/configurations/{id}/snippets/{snippetId}][%d] deleteSnippetNotFound ", 404)
}

func (o *DeleteSnippetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
