// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOutputParams creates a new DeleteOutputParams object
// with the default values initialized.
func NewDeleteOutputParams() *DeleteOutputParams {
	var ()
	return &DeleteOutputParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOutputParamsWithTimeout creates a new DeleteOutputParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOutputParamsWithTimeout(timeout time.Duration) *DeleteOutputParams {
	var ()
	return &DeleteOutputParams{

		timeout: timeout,
	}
}

// NewDeleteOutputParamsWithContext creates a new DeleteOutputParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOutputParamsWithContext(ctx context.Context) *DeleteOutputParams {
	var ()
	return &DeleteOutputParams{

		Context: ctx,
	}
}

// NewDeleteOutputParamsWithHTTPClient creates a new DeleteOutputParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOutputParamsWithHTTPClient(client *http.Client) *DeleteOutputParams {
	var ()
	return &DeleteOutputParams{
		HTTPClient: client,
	}
}

/*DeleteOutputParams contains all the parameters to send to the API endpoint
for the delete output operation typically these are written to a http.Request
*/
type DeleteOutputParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete output params
func (o *DeleteOutputParams) WithTimeout(timeout time.Duration) *DeleteOutputParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete output params
func (o *DeleteOutputParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete output params
func (o *DeleteOutputParams) WithContext(ctx context.Context) *DeleteOutputParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete output params
func (o *DeleteOutputParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete output params
func (o *DeleteOutputParams) WithHTTPClient(client *http.Client) *DeleteOutputParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete output params
func (o *DeleteOutputParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete output params
func (o *DeleteOutputParams) WithID(id string) *DeleteOutputParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete output params
func (o *DeleteOutputParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOutputParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
