// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteInputReader is a Reader for the DeleteInput structure.
type DeleteInputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteInputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInputBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteInputNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInputOK creates a DeleteInputOK with default headers values
func NewDeleteInputOK() *DeleteInputOK {
	return &DeleteInputOK{}
}

/*DeleteInputOK handles this case with default header values.

No response was specified
*/
type DeleteInputOK struct {
}

func (o *DeleteInputOK) Error() string {
	return fmt.Sprintf("[DELETE /plugins/org.graylog.plugins.collector/configurations/{id}/inputs/{inputId}][%d] deleteInputOK ", 200)
}

func (o *DeleteInputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInputBadRequest creates a DeleteInputBadRequest with default headers values
func NewDeleteInputBadRequest() *DeleteInputBadRequest {
	return &DeleteInputBadRequest{}
}

/*DeleteInputBadRequest handles this case with default header values.

Invalid ObjectId.
*/
type DeleteInputBadRequest struct {
}

func (o *DeleteInputBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /plugins/org.graylog.plugins.collector/configurations/{id}/inputs/{inputId}][%d] deleteInputBadRequest ", 400)
}

func (o *DeleteInputBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInputNotFound creates a DeleteInputNotFound with default headers values
func NewDeleteInputNotFound() *DeleteInputNotFound {
	return &DeleteInputNotFound{}
}

/*DeleteInputNotFound handles this case with default header values.

Configuration or Input not found.
*/
type DeleteInputNotFound struct {
}

func (o *DeleteInputNotFound) Error() string {
	return fmt.Sprintf("[DELETE /plugins/org.graylog.plugins.collector/configurations/{id}/inputs/{inputId}][%d] deleteInputNotFound ", 404)
}

func (o *DeleteInputNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
