// Code generated by go-swagger; DO NOT EDIT.

package plugins_map_mapdata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateSnippetReader is a Reader for the UpdateSnippet structure.
type UpdateSnippetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSnippetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateSnippetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateSnippetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSnippetOK creates a UpdateSnippetOK with default headers values
func NewUpdateSnippetOK() *UpdateSnippetOK {
	return &UpdateSnippetOK{}
}

/*UpdateSnippetOK handles this case with default header values.

No response was specified
*/
type UpdateSnippetOK struct {
}

func (o *UpdateSnippetOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/org.graylog.plugins.collector/configurations/{id}/snippets/{snippet_id}][%d] updateSnippetOK ", 200)
}

func (o *UpdateSnippetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSnippetBadRequest creates a UpdateSnippetBadRequest with default headers values
func NewUpdateSnippetBadRequest() *UpdateSnippetBadRequest {
	return &UpdateSnippetBadRequest{}
}

/*UpdateSnippetBadRequest handles this case with default header values.

The supplied request is not valid.
*/
type UpdateSnippetBadRequest struct {
}

func (o *UpdateSnippetBadRequest) Error() string {
	return fmt.Sprintf("[PUT /plugins/org.graylog.plugins.collector/configurations/{id}/snippets/{snippet_id}][%d] updateSnippetBadRequest ", 400)
}

func (o *UpdateSnippetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
