// Code generated by go-swagger; DO NOT EDIT.

package dashboards_dashboard_id_widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// WidgetValueReader is a Reader for the WidgetValue structure.
type WidgetValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WidgetValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWidgetValueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewWidgetValueNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewWidgetValueGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWidgetValueOK creates a WidgetValueOK with default headers values
func NewWidgetValueOK() *WidgetValueOK {
	return &WidgetValueOK{}
}

/*WidgetValueOK handles this case with default header values.

No response was specified
*/
type WidgetValueOK struct {
	Payload WidgetValueOKBody
}

func (o *WidgetValueOK) Error() string {
	return fmt.Sprintf("[GET /dashboards/{dashboardId}/widgets/{widgetId}/value][%d] widgetValueOK  %+v", 200, o.Payload)
}

func (o *WidgetValueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWidgetValueNotFound creates a WidgetValueNotFound with default headers values
func NewWidgetValueNotFound() *WidgetValueNotFound {
	return &WidgetValueNotFound{}
}

/*WidgetValueNotFound handles this case with default header values.

Widget not found.
*/
type WidgetValueNotFound struct {
}

func (o *WidgetValueNotFound) Error() string {
	return fmt.Sprintf("[GET /dashboards/{dashboardId}/widgets/{widgetId}/value][%d] widgetValueNotFound ", 404)
}

func (o *WidgetValueNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWidgetValueGatewayTimeout creates a WidgetValueGatewayTimeout with default headers values
func NewWidgetValueGatewayTimeout() *WidgetValueGatewayTimeout {
	return &WidgetValueGatewayTimeout{}
}

/*WidgetValueGatewayTimeout handles this case with default header values.

Computation failed on indexer side.
*/
type WidgetValueGatewayTimeout struct {
}

func (o *WidgetValueGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /dashboards/{dashboardId}/widgets/{widgetId}/value][%d] widgetValueGatewayTimeout ", 504)
}

func (o *WidgetValueGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*WidgetValueOKBody widget value o k body
swagger:model WidgetValueOKBody
*/
type WidgetValueOKBody interface{}
