// Code generated by go-swagger; DO NOT EDIT.

package system_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new system notifications API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for system notifications API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
HistoricSingleMetric gets history of a single metric

The maximum retention time is currently only 5 minutes.
*/
func (a *Client) HistoricSingleMetric(params *HistoricSingleMetricParams, authInfo runtime.ClientAuthInfoWriter) (*HistoricSingleMetricOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHistoricSingleMetricParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "historicSingleMetric",
		Method:             "GET",
		PathPattern:        "/system/metrics/{metricName}/history",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HistoricSingleMetricReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*HistoricSingleMetricOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
