// Code generated by go-swagger; DO NOT EDIT.

package system_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// ThreaddumpReader is a Reader for the Threaddump structure.
type ThreaddumpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThreaddumpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewThreaddumpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewThreaddumpOK creates a ThreaddumpOK with default headers values
func NewThreaddumpOK() *ThreaddumpOK {
	return &ThreaddumpOK{}
}

/*ThreaddumpOK handles this case with default header values.

No response was specified
*/
type ThreaddumpOK struct {
	Payload *models.SystemThreadDumpResponse
}

func (o *ThreaddumpOK) Error() string {
	return fmt.Sprintf("[GET /system/threaddump][%d] threaddumpOK  %+v", 200, o.Payload)
}

func (o *ThreaddumpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SystemThreadDumpResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
