// Code generated by go-swagger; DO NOT EDIT.

package system_metrics_metric_name_history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSingleMetricParams creates a new SingleMetricParams object
// with the default values initialized.
func NewSingleMetricParams() *SingleMetricParams {
	var ()
	return &SingleMetricParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSingleMetricParamsWithTimeout creates a new SingleMetricParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSingleMetricParamsWithTimeout(timeout time.Duration) *SingleMetricParams {
	var ()
	return &SingleMetricParams{

		timeout: timeout,
	}
}

// NewSingleMetricParamsWithContext creates a new SingleMetricParams object
// with the default values initialized, and the ability to set a context for a request
func NewSingleMetricParamsWithContext(ctx context.Context) *SingleMetricParams {
	var ()
	return &SingleMetricParams{

		Context: ctx,
	}
}

// NewSingleMetricParamsWithHTTPClient creates a new SingleMetricParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSingleMetricParamsWithHTTPClient(client *http.Client) *SingleMetricParams {
	var ()
	return &SingleMetricParams{
		HTTPClient: client,
	}
}

/*SingleMetricParams contains all the parameters to send to the API endpoint
for the single metric operation typically these are written to a http.Request
*/
type SingleMetricParams struct {

	/*MetricName*/
	MetricName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the single metric params
func (o *SingleMetricParams) WithTimeout(timeout time.Duration) *SingleMetricParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the single metric params
func (o *SingleMetricParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the single metric params
func (o *SingleMetricParams) WithContext(ctx context.Context) *SingleMetricParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the single metric params
func (o *SingleMetricParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the single metric params
func (o *SingleMetricParams) WithHTTPClient(client *http.Client) *SingleMetricParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the single metric params
func (o *SingleMetricParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetricName adds the metricName to the single metric params
func (o *SingleMetricParams) WithMetricName(metricName string) *SingleMetricParams {
	o.SetMetricName(metricName)
	return o
}

// SetMetricName adds the metricName to the single metric params
func (o *SingleMetricParams) SetMetricName(metricName string) {
	o.MetricName = metricName
}

// WriteToRequest writes these params to a swagger request
func (o *SingleMetricParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param metricName
	if err := r.SetPathParam("metricName", o.MetricName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
