// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AvailableCacheTypesReader is a Reader for the AvailableCacheTypes structure.
type AvailableCacheTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvailableCacheTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAvailableCacheTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAvailableCacheTypesOK creates a AvailableCacheTypesOK with default headers values
func NewAvailableCacheTypesOK() *AvailableCacheTypesOK {
	return &AvailableCacheTypesOK{}
}

/*AvailableCacheTypesOK handles this case with default header values.

No response was specified
*/
type AvailableCacheTypesOK struct {
	Payload AvailableCacheTypesOKBody
}

func (o *AvailableCacheTypesOK) Error() string {
	return fmt.Sprintf("[GET /system/lookup/types/caches][%d] availableCacheTypesOK  %+v", 200, o.Payload)
}

func (o *AvailableCacheTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*AvailableCacheTypesOKBody available cache types o k body
swagger:model AvailableCacheTypesOKBody
*/
type AvailableCacheTypesOKBody interface{}
