// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAvailableCacheTypesParams creates a new AvailableCacheTypesParams object
// with the default values initialized.
func NewAvailableCacheTypesParams() *AvailableCacheTypesParams {

	return &AvailableCacheTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAvailableCacheTypesParamsWithTimeout creates a new AvailableCacheTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAvailableCacheTypesParamsWithTimeout(timeout time.Duration) *AvailableCacheTypesParams {

	return &AvailableCacheTypesParams{

		timeout: timeout,
	}
}

// NewAvailableCacheTypesParamsWithContext creates a new AvailableCacheTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewAvailableCacheTypesParamsWithContext(ctx context.Context) *AvailableCacheTypesParams {

	return &AvailableCacheTypesParams{

		Context: ctx,
	}
}

// NewAvailableCacheTypesParamsWithHTTPClient creates a new AvailableCacheTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAvailableCacheTypesParamsWithHTTPClient(client *http.Client) *AvailableCacheTypesParams {

	return &AvailableCacheTypesParams{
		HTTPClient: client,
	}
}

/*AvailableCacheTypesParams contains all the parameters to send to the API endpoint
for the available cache types operation typically these are written to a http.Request
*/
type AvailableCacheTypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the available cache types params
func (o *AvailableCacheTypesParams) WithTimeout(timeout time.Duration) *AvailableCacheTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the available cache types params
func (o *AvailableCacheTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the available cache types params
func (o *AvailableCacheTypesParams) WithContext(ctx context.Context) *AvailableCacheTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the available cache types params
func (o *AvailableCacheTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the available cache types params
func (o *AvailableCacheTypesParams) WithHTTPClient(client *http.Client) *AvailableCacheTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the available cache types params
func (o *AvailableCacheTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AvailableCacheTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
