// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// NewCreateAdapterParams creates a new CreateAdapterParams object
// with the default values initialized.
func NewCreateAdapterParams() *CreateAdapterParams {
	var ()
	return &CreateAdapterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAdapterParamsWithTimeout creates a new CreateAdapterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAdapterParamsWithTimeout(timeout time.Duration) *CreateAdapterParams {
	var ()
	return &CreateAdapterParams{

		timeout: timeout,
	}
}

// NewCreateAdapterParamsWithContext creates a new CreateAdapterParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAdapterParamsWithContext(ctx context.Context) *CreateAdapterParams {
	var ()
	return &CreateAdapterParams{

		Context: ctx,
	}
}

// NewCreateAdapterParamsWithHTTPClient creates a new CreateAdapterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAdapterParamsWithHTTPClient(client *http.Client) *CreateAdapterParams {
	var ()
	return &CreateAdapterParams{
		HTTPClient: client,
	}
}

/*CreateAdapterParams contains all the parameters to send to the API endpoint
for the create adapter operation typically these are written to a http.Request
*/
type CreateAdapterParams struct {

	/*Body*/
	Body *models.DataAdapterAPI

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create adapter params
func (o *CreateAdapterParams) WithTimeout(timeout time.Duration) *CreateAdapterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create adapter params
func (o *CreateAdapterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create adapter params
func (o *CreateAdapterParams) WithContext(ctx context.Context) *CreateAdapterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create adapter params
func (o *CreateAdapterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create adapter params
func (o *CreateAdapterParams) WithHTTPClient(client *http.Client) *CreateAdapterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create adapter params
func (o *CreateAdapterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create adapter params
func (o *CreateAdapterParams) WithBody(body *models.DataAdapterAPI) *CreateAdapterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create adapter params
func (o *CreateAdapterParams) SetBody(body *models.DataAdapterAPI) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAdapterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
