// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// NewErrorStatesParams creates a new ErrorStatesParams object
// with the default values initialized.
func NewErrorStatesParams() *ErrorStatesParams {
	var ()
	return &ErrorStatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewErrorStatesParamsWithTimeout creates a new ErrorStatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewErrorStatesParamsWithTimeout(timeout time.Duration) *ErrorStatesParams {
	var ()
	return &ErrorStatesParams{

		timeout: timeout,
	}
}

// NewErrorStatesParamsWithContext creates a new ErrorStatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewErrorStatesParamsWithContext(ctx context.Context) *ErrorStatesParams {
	var ()
	return &ErrorStatesParams{

		Context: ctx,
	}
}

// NewErrorStatesParamsWithHTTPClient creates a new ErrorStatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewErrorStatesParamsWithHTTPClient(client *http.Client) *ErrorStatesParams {
	var ()
	return &ErrorStatesParams{
		HTTPClient: client,
	}
}

/*ErrorStatesParams contains all the parameters to send to the API endpoint
for the error states operation typically these are written to a http.Request
*/
type ErrorStatesParams struct {

	/*Request*/
	Request *models.ErrorStatesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the error states params
func (o *ErrorStatesParams) WithTimeout(timeout time.Duration) *ErrorStatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the error states params
func (o *ErrorStatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the error states params
func (o *ErrorStatesParams) WithContext(ctx context.Context) *ErrorStatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the error states params
func (o *ErrorStatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the error states params
func (o *ErrorStatesParams) WithHTTPClient(client *http.Client) *ErrorStatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the error states params
func (o *ErrorStatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the error states params
func (o *ErrorStatesParams) WithRequest(request *models.ErrorStatesRequest) *ErrorStatesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the error states params
func (o *ErrorStatesParams) SetRequest(request *models.ErrorStatesRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ErrorStatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
