// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPerformPurgeParams creates a new PerformPurgeParams object
// with the default values initialized.
func NewPerformPurgeParams() *PerformPurgeParams {
	var ()
	return &PerformPurgeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPerformPurgeParamsWithTimeout creates a new PerformPurgeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPerformPurgeParamsWithTimeout(timeout time.Duration) *PerformPurgeParams {
	var ()
	return &PerformPurgeParams{

		timeout: timeout,
	}
}

// NewPerformPurgeParamsWithContext creates a new PerformPurgeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPerformPurgeParamsWithContext(ctx context.Context) *PerformPurgeParams {
	var ()
	return &PerformPurgeParams{

		Context: ctx,
	}
}

// NewPerformPurgeParamsWithHTTPClient creates a new PerformPurgeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPerformPurgeParamsWithHTTPClient(client *http.Client) *PerformPurgeParams {
	var ()
	return &PerformPurgeParams{
		HTTPClient: client,
	}
}

/*PerformPurgeParams contains all the parameters to send to the API endpoint
for the perform purge operation typically these are written to a http.Request
*/
type PerformPurgeParams struct {

	/*IDOrName*/
	IDOrName string
	/*Key*/
	Key *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the perform purge params
func (o *PerformPurgeParams) WithTimeout(timeout time.Duration) *PerformPurgeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the perform purge params
func (o *PerformPurgeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the perform purge params
func (o *PerformPurgeParams) WithContext(ctx context.Context) *PerformPurgeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the perform purge params
func (o *PerformPurgeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the perform purge params
func (o *PerformPurgeParams) WithHTTPClient(client *http.Client) *PerformPurgeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the perform purge params
func (o *PerformPurgeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIDOrName adds the iDOrName to the perform purge params
func (o *PerformPurgeParams) WithIDOrName(iDOrName string) *PerformPurgeParams {
	o.SetIDOrName(iDOrName)
	return o
}

// SetIDOrName adds the idOrName to the perform purge params
func (o *PerformPurgeParams) SetIDOrName(iDOrName string) {
	o.IDOrName = iDOrName
}

// WithKey adds the key to the perform purge params
func (o *PerformPurgeParams) WithKey(key *string) *PerformPurgeParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the perform purge params
func (o *PerformPurgeParams) SetKey(key *string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *PerformPurgeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param idOrName
	if err := r.SetPathParam("idOrName", o.IDOrName); err != nil {
		return err
	}

	if o.Key != nil {

		// query param key
		var qrKey string
		if o.Key != nil {
			qrKey = *o.Key
		}
		qKey := qrKey
		if qKey != "" {
			if err := r.SetQueryParam("key", qKey); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
