// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPerformAdapterLookupParams creates a new PerformAdapterLookupParams object
// with the default values initialized.
func NewPerformAdapterLookupParams() *PerformAdapterLookupParams {
	var ()
	return &PerformAdapterLookupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPerformAdapterLookupParamsWithTimeout creates a new PerformAdapterLookupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPerformAdapterLookupParamsWithTimeout(timeout time.Duration) *PerformAdapterLookupParams {
	var ()
	return &PerformAdapterLookupParams{

		timeout: timeout,
	}
}

// NewPerformAdapterLookupParamsWithContext creates a new PerformAdapterLookupParams object
// with the default values initialized, and the ability to set a context for a request
func NewPerformAdapterLookupParamsWithContext(ctx context.Context) *PerformAdapterLookupParams {
	var ()
	return &PerformAdapterLookupParams{

		Context: ctx,
	}
}

// NewPerformAdapterLookupParamsWithHTTPClient creates a new PerformAdapterLookupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPerformAdapterLookupParamsWithHTTPClient(client *http.Client) *PerformAdapterLookupParams {
	var ()
	return &PerformAdapterLookupParams{
		HTTPClient: client,
	}
}

/*PerformAdapterLookupParams contains all the parameters to send to the API endpoint
for the perform adapter lookup operation typically these are written to a http.Request
*/
type PerformAdapterLookupParams struct {

	/*Key*/
	Key *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the perform adapter lookup params
func (o *PerformAdapterLookupParams) WithTimeout(timeout time.Duration) *PerformAdapterLookupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the perform adapter lookup params
func (o *PerformAdapterLookupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the perform adapter lookup params
func (o *PerformAdapterLookupParams) WithContext(ctx context.Context) *PerformAdapterLookupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the perform adapter lookup params
func (o *PerformAdapterLookupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the perform adapter lookup params
func (o *PerformAdapterLookupParams) WithHTTPClient(client *http.Client) *PerformAdapterLookupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the perform adapter lookup params
func (o *PerformAdapterLookupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the perform adapter lookup params
func (o *PerformAdapterLookupParams) WithKey(key *string) *PerformAdapterLookupParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the perform adapter lookup params
func (o *PerformAdapterLookupParams) SetKey(key *string) {
	o.Key = key
}

// WithName adds the name to the perform adapter lookup params
func (o *PerformAdapterLookupParams) WithName(name string) *PerformAdapterLookupParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the perform adapter lookup params
func (o *PerformAdapterLookupParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PerformAdapterLookupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Key != nil {

		// query param key
		var qrKey string
		if o.Key != nil {
			qrKey = *o.Key
		}
		qKey := qrKey
		if qKey != "" {
			if err := r.SetQueryParam("key", qKey); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
