// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// TablesReader is a Reader for the Tables structure.
type TablesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TablesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTablesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTablesOK creates a TablesOK with default headers values
func NewTablesOK() *TablesOK {
	return &TablesOK{}
}

/*TablesOK handles this case with default header values.

No response was specified
*/
type TablesOK struct {
	Payload *models.LookupTablePage
}

func (o *TablesOK) Error() string {
	return fmt.Sprintf("[GET /system/lookup/tables][%d] tablesOK  %+v", 200, o.Payload)
}

func (o *TablesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LookupTablePage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
