// Code generated by go-swagger; DO NOT EDIT.

package system_messageprocessors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// NewUpdateAdapterParams creates a new UpdateAdapterParams object
// with the default values initialized.
func NewUpdateAdapterParams() *UpdateAdapterParams {
	var ()
	return &UpdateAdapterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAdapterParamsWithTimeout creates a new UpdateAdapterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAdapterParamsWithTimeout(timeout time.Duration) *UpdateAdapterParams {
	var ()
	return &UpdateAdapterParams{

		timeout: timeout,
	}
}

// NewUpdateAdapterParamsWithContext creates a new UpdateAdapterParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAdapterParamsWithContext(ctx context.Context) *UpdateAdapterParams {
	var ()
	return &UpdateAdapterParams{

		Context: ctx,
	}
}

// NewUpdateAdapterParamsWithHTTPClient creates a new UpdateAdapterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAdapterParamsWithHTTPClient(client *http.Client) *UpdateAdapterParams {
	var ()
	return &UpdateAdapterParams{
		HTTPClient: client,
	}
}

/*UpdateAdapterParams contains all the parameters to send to the API endpoint
for the update adapter operation typically these are written to a http.Request
*/
type UpdateAdapterParams struct {

	/*Body*/
	Body *models.DataAdapterAPI
	/*IDOrName*/
	IDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update adapter params
func (o *UpdateAdapterParams) WithTimeout(timeout time.Duration) *UpdateAdapterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update adapter params
func (o *UpdateAdapterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update adapter params
func (o *UpdateAdapterParams) WithContext(ctx context.Context) *UpdateAdapterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update adapter params
func (o *UpdateAdapterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update adapter params
func (o *UpdateAdapterParams) WithHTTPClient(client *http.Client) *UpdateAdapterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update adapter params
func (o *UpdateAdapterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update adapter params
func (o *UpdateAdapterParams) WithBody(body *models.DataAdapterAPI) *UpdateAdapterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update adapter params
func (o *UpdateAdapterParams) SetBody(body *models.DataAdapterAPI) {
	o.Body = body
}

// WithIDOrName adds the iDOrName to the update adapter params
func (o *UpdateAdapterParams) WithIDOrName(iDOrName string) *UpdateAdapterParams {
	o.SetIDOrName(iDOrName)
	return o
}

// SetIDOrName adds the idOrName to the update adapter params
func (o *UpdateAdapterParams) SetIDOrName(iDOrName string) {
	o.IDOrName = iDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAdapterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param idOrName
	if err := r.SetPathParam("idOrName", o.IDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
