// Code generated by go-swagger; DO NOT EDIT.

package system_throughput

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOsStatsParams creates a new OsStatsParams object
// with the default values initialized.
func NewOsStatsParams() *OsStatsParams {

	return &OsStatsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOsStatsParamsWithTimeout creates a new OsStatsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOsStatsParamsWithTimeout(timeout time.Duration) *OsStatsParams {

	return &OsStatsParams{

		timeout: timeout,
	}
}

// NewOsStatsParamsWithContext creates a new OsStatsParams object
// with the default values initialized, and the ability to set a context for a request
func NewOsStatsParamsWithContext(ctx context.Context) *OsStatsParams {

	return &OsStatsParams{

		Context: ctx,
	}
}

// NewOsStatsParamsWithHTTPClient creates a new OsStatsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOsStatsParamsWithHTTPClient(client *http.Client) *OsStatsParams {

	return &OsStatsParams{
		HTTPClient: client,
	}
}

/*OsStatsParams contains all the parameters to send to the API endpoint
for the os stats operation typically these are written to a http.Request
*/
type OsStatsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the os stats params
func (o *OsStatsParams) WithTimeout(timeout time.Duration) *OsStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the os stats params
func (o *OsStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the os stats params
func (o *OsStatsParams) WithContext(ctx context.Context) *OsStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the os stats params
func (o *OsStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the os stats params
func (o *OsStatsParams) WithHTTPClient(client *http.Client) *OsStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the os stats params
func (o *OsStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OsStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
