// Code generated by go-swagger; DO NOT EDIT.

package system_throughput

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// ProcessStatsReader is a Reader for the ProcessStats structure.
type ProcessStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProcessStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProcessStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProcessStatsOK creates a ProcessStatsOK with default headers values
func NewProcessStatsOK() *ProcessStatsOK {
	return &ProcessStatsOK{}
}

/*ProcessStatsOK handles this case with default header values.

No response was specified
*/
type ProcessStatsOK struct {
	Payload *models.ProcessStats
}

func (o *ProcessStatsOK) Error() string {
	return fmt.Sprintf("[GET /system/stats/process][%d] processStatsOK  %+v", 200, o.Payload)
}

func (o *ProcessStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStats)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
