// Code generated by go-swagger; DO NOT EDIT.

package plugins_system_pipelines_simulate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// ParseReader is a Reader for the Parse structure.
type ParseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ParseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewParseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewParseOK creates a ParseOK with default headers values
func NewParseOK() *ParseOK {
	return &ParseOK{}
}

/*ParseOK handles this case with default header values.

No response was specified
*/
type ParseOK struct {
	Payload *models.RuleSource
}

func (o *ParseOK) Error() string {
	return fmt.Sprintf("[POST /plugins/org.graylog.plugins.pipelineprocessor/system/pipelines/rule/parse][%d] parseOK  %+v", 200, o.Payload)
}

func (o *ParseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuleSource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
