// Code generated by go-swagger; DO NOT EDIT.

package search_decorators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// SearchAbsoluteReader is a Reader for the SearchAbsolute structure.
type SearchAbsoluteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchAbsoluteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchAbsoluteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSearchAbsoluteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchAbsoluteOK creates a SearchAbsoluteOK with default headers values
func NewSearchAbsoluteOK() *SearchAbsoluteOK {
	return &SearchAbsoluteOK{}
}

/*SearchAbsoluteOK handles this case with default header values.

No response was specified
*/
type SearchAbsoluteOK struct {
	Payload *models.SearchResponse
}

func (o *SearchAbsoluteOK) Error() string {
	return fmt.Sprintf("[GET /search/universal/absolute][%d] searchAbsoluteOK  %+v", 200, o.Payload)
}

func (o *SearchAbsoluteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAbsoluteBadRequest creates a SearchAbsoluteBadRequest with default headers values
func NewSearchAbsoluteBadRequest() *SearchAbsoluteBadRequest {
	return &SearchAbsoluteBadRequest{}
}

/*SearchAbsoluteBadRequest handles this case with default header values.

Invalid timerange parameters provided.
*/
type SearchAbsoluteBadRequest struct {
}

func (o *SearchAbsoluteBadRequest) Error() string {
	return fmt.Sprintf("[GET /search/universal/absolute][%d] searchAbsoluteBadRequest ", 400)
}

func (o *SearchAbsoluteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
