// Code generated by go-swagger; DO NOT EDIT.

package system_shutdown

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// ValidateSessionReader is a Reader for the ValidateSession structure.
type ValidateSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewValidateSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateSessionOK creates a ValidateSessionOK with default headers values
func NewValidateSessionOK() *ValidateSessionOK {
	return &ValidateSessionOK{}
}

/*ValidateSessionOK handles this case with default header values.

No response was specified
*/
type ValidateSessionOK struct {
	Payload *models.SessionValidationResponse
}

func (o *ValidateSessionOK) Error() string {
	return fmt.Sprintf("[GET /system/sessions][%d] validateSessionOK  %+v", 200, o.Payload)
}

func (o *ValidateSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionValidationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
