// Code generated by go-swagger; DO NOT EDIT.

package system_deflector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGenerateDebugEventParams creates a new GenerateDebugEventParams object
// with the default values initialized.
func NewGenerateDebugEventParams() *GenerateDebugEventParams {
	var ()
	return &GenerateDebugEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateDebugEventParamsWithTimeout creates a new GenerateDebugEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGenerateDebugEventParamsWithTimeout(timeout time.Duration) *GenerateDebugEventParams {
	var ()
	return &GenerateDebugEventParams{

		timeout: timeout,
	}
}

// NewGenerateDebugEventParamsWithContext creates a new GenerateDebugEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewGenerateDebugEventParamsWithContext(ctx context.Context) *GenerateDebugEventParams {
	var ()
	return &GenerateDebugEventParams{

		Context: ctx,
	}
}

// NewGenerateDebugEventParamsWithHTTPClient creates a new GenerateDebugEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGenerateDebugEventParamsWithHTTPClient(client *http.Client) *GenerateDebugEventParams {
	var ()
	return &GenerateDebugEventParams{
		HTTPClient: client,
	}
}

/*GenerateDebugEventParams contains all the parameters to send to the API endpoint
for the generate debug event operation typically these are written to a http.Request
*/
type GenerateDebugEventParams struct {

	/*Text*/
	Text *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the generate debug event params
func (o *GenerateDebugEventParams) WithTimeout(timeout time.Duration) *GenerateDebugEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate debug event params
func (o *GenerateDebugEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate debug event params
func (o *GenerateDebugEventParams) WithContext(ctx context.Context) *GenerateDebugEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate debug event params
func (o *GenerateDebugEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate debug event params
func (o *GenerateDebugEventParams) WithHTTPClient(client *http.Client) *GenerateDebugEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate debug event params
func (o *GenerateDebugEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithText adds the text to the generate debug event params
func (o *GenerateDebugEventParams) WithText(text *string) *GenerateDebugEventParams {
	o.SetText(text)
	return o
}

// SetText adds the text to the generate debug event params
func (o *GenerateDebugEventParams) SetText(text *string) {
	o.Text = text
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateDebugEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Text != nil {
		if err := r.SetBodyParam(o.Text); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
