// Code generated by go-swagger; DO NOT EDIT.

package system_deflector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GenerateDebugEventReader is a Reader for the GenerateDebugEvent structure.
type GenerateDebugEventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateDebugEventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGenerateDebugEventOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGenerateDebugEventOK creates a GenerateDebugEventOK with default headers values
func NewGenerateDebugEventOK() *GenerateDebugEventOK {
	return &GenerateDebugEventOK{}
}

/*GenerateDebugEventOK handles this case with default header values.

No response was specified
*/
type GenerateDebugEventOK struct {
}

func (o *GenerateDebugEventOK) Error() string {
	return fmt.Sprintf("[POST /system/debug/events/local][%d] generateDebugEventOK ", 200)
}

func (o *GenerateDebugEventOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
