// Code generated by go-swagger; DO NOT EDIT.

package system_deflector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowLastDebugEventParams creates a new ShowLastDebugEventParams object
// with the default values initialized.
func NewShowLastDebugEventParams() *ShowLastDebugEventParams {

	return &ShowLastDebugEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowLastDebugEventParamsWithTimeout creates a new ShowLastDebugEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowLastDebugEventParamsWithTimeout(timeout time.Duration) *ShowLastDebugEventParams {

	return &ShowLastDebugEventParams{

		timeout: timeout,
	}
}

// NewShowLastDebugEventParamsWithContext creates a new ShowLastDebugEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowLastDebugEventParamsWithContext(ctx context.Context) *ShowLastDebugEventParams {

	return &ShowLastDebugEventParams{

		Context: ctx,
	}
}

// NewShowLastDebugEventParamsWithHTTPClient creates a new ShowLastDebugEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowLastDebugEventParamsWithHTTPClient(client *http.Client) *ShowLastDebugEventParams {

	return &ShowLastDebugEventParams{
		HTTPClient: client,
	}
}

/*ShowLastDebugEventParams contains all the parameters to send to the API endpoint
for the show last debug event operation typically these are written to a http.Request
*/
type ShowLastDebugEventParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show last debug event params
func (o *ShowLastDebugEventParams) WithTimeout(timeout time.Duration) *ShowLastDebugEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show last debug event params
func (o *ShowLastDebugEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show last debug event params
func (o *ShowLastDebugEventParams) WithContext(ctx context.Context) *ShowLastDebugEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show last debug event params
func (o *ShowLastDebugEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show last debug event params
func (o *ShowLastDebugEventParams) WithHTTPClient(client *http.Client) *ShowLastDebugEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show last debug event params
func (o *ShowLastDebugEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ShowLastDebugEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
