// Code generated by go-swagger; DO NOT EDIT.

package search_universal_relative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHistogramKeywordParams creates a new HistogramKeywordParams object
// with the default values initialized.
func NewHistogramKeywordParams() *HistogramKeywordParams {
	var ()
	return &HistogramKeywordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHistogramKeywordParamsWithTimeout creates a new HistogramKeywordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHistogramKeywordParamsWithTimeout(timeout time.Duration) *HistogramKeywordParams {
	var ()
	return &HistogramKeywordParams{

		timeout: timeout,
	}
}

// NewHistogramKeywordParamsWithContext creates a new HistogramKeywordParams object
// with the default values initialized, and the ability to set a context for a request
func NewHistogramKeywordParamsWithContext(ctx context.Context) *HistogramKeywordParams {
	var ()
	return &HistogramKeywordParams{

		Context: ctx,
	}
}

// NewHistogramKeywordParamsWithHTTPClient creates a new HistogramKeywordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHistogramKeywordParamsWithHTTPClient(client *http.Client) *HistogramKeywordParams {
	var ()
	return &HistogramKeywordParams{
		HTTPClient: client,
	}
}

/*HistogramKeywordParams contains all the parameters to send to the API endpoint
for the histogram keyword operation typically these are written to a http.Request
*/
type HistogramKeywordParams struct {

	/*Filter
	  Filter

	*/
	Filter *string
	/*Interval
	  Histogram interval / bucket size. (year, quarter, month, week, day, hour or minute)

	*/
	Interval string
	/*Keyword
	  Range keyword

	*/
	Keyword string
	/*Query
	  Query (Lucene syntax)

	*/
	Query string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the histogram keyword params
func (o *HistogramKeywordParams) WithTimeout(timeout time.Duration) *HistogramKeywordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the histogram keyword params
func (o *HistogramKeywordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the histogram keyword params
func (o *HistogramKeywordParams) WithContext(ctx context.Context) *HistogramKeywordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the histogram keyword params
func (o *HistogramKeywordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the histogram keyword params
func (o *HistogramKeywordParams) WithHTTPClient(client *http.Client) *HistogramKeywordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the histogram keyword params
func (o *HistogramKeywordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the histogram keyword params
func (o *HistogramKeywordParams) WithFilter(filter *string) *HistogramKeywordParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the histogram keyword params
func (o *HistogramKeywordParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithInterval adds the interval to the histogram keyword params
func (o *HistogramKeywordParams) WithInterval(interval string) *HistogramKeywordParams {
	o.SetInterval(interval)
	return o
}

// SetInterval adds the interval to the histogram keyword params
func (o *HistogramKeywordParams) SetInterval(interval string) {
	o.Interval = interval
}

// WithKeyword adds the keyword to the histogram keyword params
func (o *HistogramKeywordParams) WithKeyword(keyword string) *HistogramKeywordParams {
	o.SetKeyword(keyword)
	return o
}

// SetKeyword adds the keyword to the histogram keyword params
func (o *HistogramKeywordParams) SetKeyword(keyword string) {
	o.Keyword = keyword
}

// WithQuery adds the query to the histogram keyword params
func (o *HistogramKeywordParams) WithQuery(query string) *HistogramKeywordParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the histogram keyword params
func (o *HistogramKeywordParams) SetQuery(query string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *HistogramKeywordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	// query param interval
	qrInterval := o.Interval
	qInterval := qrInterval
	if qInterval != "" {
		if err := r.SetQueryParam("interval", qInterval); err != nil {
			return err
		}
	}

	// query param keyword
	qrKeyword := o.Keyword
	qKeyword := qrKeyword
	if qKeyword != "" {
		if err := r.SetQueryParam("keyword", qKeyword); err != nil {
			return err
		}
	}

	// query param query
	qrQuery := o.Query
	qQuery := qrQuery
	if qQuery != "" {
		if err := r.SetQueryParam("query", qQuery); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
