// Code generated by go-swagger; DO NOT EDIT.

package search_universal_relative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// TermsKeywordReader is a Reader for the TermsKeyword structure.
type TermsKeywordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TermsKeywordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTermsKeywordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewTermsKeywordBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTermsKeywordOK creates a TermsKeywordOK with default headers values
func NewTermsKeywordOK() *TermsKeywordOK {
	return &TermsKeywordOK{}
}

/*TermsKeywordOK handles this case with default header values.

No response was specified
*/
type TermsKeywordOK struct {
	Payload *models.TermsResult
}

func (o *TermsKeywordOK) Error() string {
	return fmt.Sprintf("[GET /search/universal/keyword/terms][%d] termsKeywordOK  %+v", 200, o.Payload)
}

func (o *TermsKeywordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TermsResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTermsKeywordBadRequest creates a TermsKeywordBadRequest with default headers values
func NewTermsKeywordBadRequest() *TermsKeywordBadRequest {
	return &TermsKeywordBadRequest{}
}

/*TermsKeywordBadRequest handles this case with default header values.

Invalid timerange parameters provided.
*/
type TermsKeywordBadRequest struct {
}

func (o *TermsKeywordBadRequest) Error() string {
	return fmt.Sprintf("[GET /search/universal/keyword/terms][%d] termsKeywordBadRequest ", 400)
}

func (o *TermsKeywordBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
