// Code generated by go-swagger; DO NOT EDIT.

package system_indices_ranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RemovePatternReader is a Reader for the RemovePattern structure.
type RemovePatternReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemovePatternReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRemovePatternOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemovePatternOK creates a RemovePatternOK with default headers values
func NewRemovePatternOK() *RemovePatternOK {
	return &RemovePatternOK{}
}

/*RemovePatternOK handles this case with default header values.

No response was specified
*/
type RemovePatternOK struct {
}

func (o *RemovePatternOK) Error() string {
	return fmt.Sprintf("[DELETE /system/grok/{patternId}][%d] removePatternOK ", 200)
}

func (o *RemovePatternOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
