// Code generated by go-swagger; DO NOT EDIT.

package streams_streamid_outputs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRemoveReceiverParams creates a new RemoveReceiverParams object
// with the default values initialized.
func NewRemoveReceiverParams() *RemoveReceiverParams {
	var ()
	return &RemoveReceiverParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveReceiverParamsWithTimeout creates a new RemoveReceiverParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveReceiverParamsWithTimeout(timeout time.Duration) *RemoveReceiverParams {
	var ()
	return &RemoveReceiverParams{

		timeout: timeout,
	}
}

// NewRemoveReceiverParamsWithContext creates a new RemoveReceiverParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveReceiverParamsWithContext(ctx context.Context) *RemoveReceiverParams {
	var ()
	return &RemoveReceiverParams{

		Context: ctx,
	}
}

// NewRemoveReceiverParamsWithHTTPClient creates a new RemoveReceiverParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveReceiverParamsWithHTTPClient(client *http.Client) *RemoveReceiverParams {
	var ()
	return &RemoveReceiverParams{
		HTTPClient: client,
	}
}

/*RemoveReceiverParams contains all the parameters to send to the API endpoint
for the remove receiver operation typically these are written to a http.Request
*/
type RemoveReceiverParams struct {

	/*Entity
	  Name/ID of user or email address to remove from alert receivers.

	*/
	Entity string
	/*StreamID
	  The stream id this new alert condition belongs to.

	*/
	StreamID string
	/*Type
	  Type: users or emails

	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove receiver params
func (o *RemoveReceiverParams) WithTimeout(timeout time.Duration) *RemoveReceiverParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove receiver params
func (o *RemoveReceiverParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove receiver params
func (o *RemoveReceiverParams) WithContext(ctx context.Context) *RemoveReceiverParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove receiver params
func (o *RemoveReceiverParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove receiver params
func (o *RemoveReceiverParams) WithHTTPClient(client *http.Client) *RemoveReceiverParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove receiver params
func (o *RemoveReceiverParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEntity adds the entity to the remove receiver params
func (o *RemoveReceiverParams) WithEntity(entity string) *RemoveReceiverParams {
	o.SetEntity(entity)
	return o
}

// SetEntity adds the entity to the remove receiver params
func (o *RemoveReceiverParams) SetEntity(entity string) {
	o.Entity = entity
}

// WithStreamID adds the streamID to the remove receiver params
func (o *RemoveReceiverParams) WithStreamID(streamID string) *RemoveReceiverParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the remove receiver params
func (o *RemoveReceiverParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WithType adds the typeVar to the remove receiver params
func (o *RemoveReceiverParams) WithType(typeVar string) *RemoveReceiverParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the remove receiver params
func (o *RemoveReceiverParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveReceiverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param entity
	qrEntity := o.Entity
	qEntity := qrEntity
	if qEntity != "" {
		if err := r.SetQueryParam("entity", qEntity); err != nil {
			return err
		}
	}

	// path param streamId
	if err := r.SetPathParam("streamId", o.StreamID); err != nil {
		return err
	}

	// query param type
	qrType := o.Type
	qType := qrType
	if qType != "" {
		if err := r.SetQueryParam("type", qType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
