// Code generated by go-swagger; DO NOT EDIT.

package cluster_inputstates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new cluster inputstates API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for cluster inputstates API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
Start starts or restart specified input in all nodes
*/
func (a *Client) Start(params *StartParams, authInfo runtime.ClientAuthInfoWriter) (*StartOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStartParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "start",
		Method:             "PUT",
		PathPattern:        "/cluster/inputstates/{inputId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &StartReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StartOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
