// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/martinbaillie/go-graylog/pkg/models"
)

// NewEditPermissionsParams creates a new EditPermissionsParams object
// with the default values initialized.
func NewEditPermissionsParams() *EditPermissionsParams {
	var ()
	return &EditPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEditPermissionsParamsWithTimeout creates a new EditPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEditPermissionsParamsWithTimeout(timeout time.Duration) *EditPermissionsParams {
	var ()
	return &EditPermissionsParams{

		timeout: timeout,
	}
}

// NewEditPermissionsParamsWithContext creates a new EditPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewEditPermissionsParamsWithContext(ctx context.Context) *EditPermissionsParams {
	var ()
	return &EditPermissionsParams{

		Context: ctx,
	}
}

// NewEditPermissionsParamsWithHTTPClient creates a new EditPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEditPermissionsParamsWithHTTPClient(client *http.Client) *EditPermissionsParams {
	var ()
	return &EditPermissionsParams{
		HTTPClient: client,
	}
}

/*EditPermissionsParams contains all the parameters to send to the API endpoint
for the edit permissions operation typically these are written to a http.Request
*/
type EditPermissionsParams struct {

	/*JSONBody
	  The list of permissions to assign to the user.

	*/
	JSONBody *models.PermissionEditRequest
	/*Username
	  The name of the user to modify.

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the edit permissions params
func (o *EditPermissionsParams) WithTimeout(timeout time.Duration) *EditPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edit permissions params
func (o *EditPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edit permissions params
func (o *EditPermissionsParams) WithContext(ctx context.Context) *EditPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edit permissions params
func (o *EditPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edit permissions params
func (o *EditPermissionsParams) WithHTTPClient(client *http.Client) *EditPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edit permissions params
func (o *EditPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the edit permissions params
func (o *EditPermissionsParams) WithJSONBody(jSONBody *models.PermissionEditRequest) *EditPermissionsParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the edit permissions params
func (o *EditPermissionsParams) SetJSONBody(jSONBody *models.PermissionEditRequest) {
	o.JSONBody = jSONBody
}

// WithUsername adds the username to the edit permissions params
func (o *EditPermissionsParams) WithUsername(username string) *EditPermissionsParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the edit permissions params
func (o *EditPermissionsParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *EditPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
