// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SavePreferencesReader is a Reader for the SavePreferences structure.
type SavePreferencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SavePreferencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSavePreferencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSavePreferencesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSavePreferencesOK creates a SavePreferencesOK with default headers values
func NewSavePreferencesOK() *SavePreferencesOK {
	return &SavePreferencesOK{}
}

/*SavePreferencesOK handles this case with default header values.

No response was specified
*/
type SavePreferencesOK struct {
}

func (o *SavePreferencesOK) Error() string {
	return fmt.Sprintf("[PUT /users/{username}/preferences][%d] savePreferencesOK ", 200)
}

func (o *SavePreferencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSavePreferencesBadRequest creates a SavePreferencesBadRequest with default headers values
func NewSavePreferencesBadRequest() *SavePreferencesBadRequest {
	return &SavePreferencesBadRequest{}
}

/*SavePreferencesBadRequest handles this case with default header values.

Missing or invalid permission data.
*/
type SavePreferencesBadRequest struct {
}

func (o *SavePreferencesBadRequest) Error() string {
	return fmt.Sprintf("[PUT /users/{username}/preferences][%d] savePreferencesBadRequest ", 400)
}

func (o *SavePreferencesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
